Repository Brag-it/Bragit, pull requests merged in 2025-09, with the labels that each got.

#39 ✨ Feat: #29 선호 피드 구현
  Bragit/App/SceneDelegate.swift
  Bragit/Managers/PostManager.swift
  Bragit/Managers/StubPostManager.swift
  Bragit/Managers/TagManager.swift
  Bragit/Managers/UserManager.swift
  Bragit/Model/DependencyKeys.swift
  Bragit/Model/User.swift
  Bragit/Presentation/DesignSystem/FeedView.swift
  Bragit/Presentation/Favorite/FavoriteFeedView.swift
  Bragit/Presentation/Favorite/FavoriteMessageCell.swift
  Bragit/Presentation/Favorite/FavoriteReactor.swift
  Bragit/Presentation/Favorite/FavoriteSectionHeaderView.swift
  Bragit/Presentation/Favorite/FavoriteView.swift
  Bragit/Presentation/Favorite/FavoriteViewController.swift
  Bragit/Presentation/Home/HomeReactor.swift
  Bragit/Presentation/Home/HomeView.swift
  Bragit/Presentation/Home/HomeViewController.swift
  Bragit/Presentation/Home/PostCell.swift
  Bragit/Presentation/Home/TagsView.swift
  Bragit/Resources/Assets.xcassets/profilePerson.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/profilePerson.imageset/pic.pdf
  Bragit/Util/Reactive+.swift
Labels: ✨ Feat

#41 ✨ Feat: #40 마이페이지 비즈니스 로직 구현
  Bragit/Managers/PostManager.swift
  Bragit/Managers/StubPostManager.swift
  Bragit/Managers/UserManager.swift
  Bragit/Presentation/DesignSystem/FeedView.swift
  Bragit/Presentation/Favorite/FavoriteMessageCell.swift
  Bragit/Presentation/Favorite/FavoriteReactor.swift
  Bragit/Presentation/Favorite/FavoriteViewController.swift
  Bragit/Presentation/Home/HomeViewController.swift
  Bragit/Presentation/MyPage/MyPageReactor.swift
  Bragit/Presentation/MyPage/MyPageViewController.swift
Labels: ✨ Feat

#43 Feat/#25 terms and db save
  Bragit.xcodeproj/project.pbxproj
  Bragit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bragit/App/Flow/AppStep.swift
  Bragit/App/Flow/LoginFlow.swift
  Bragit/Presentation/ Auth/ImageUpload/ImageUploadReactor.swift
  Bragit/Presentation/ Auth/ImageUpload/ImageUploadViewController.swift
  Bragit/Presentation/ Auth/Login/LoginReactor.swift
  Bragit/Presentation/ Auth/Login/LoginViewController.swift
  Bragit/Presentation/ Auth/SignUp/UserInfoValidator.swift
  Bragit/Presentation/ Auth/SignUp/UserInfoViewController.swift
  Bragit/Presentation/ Auth/TagCheck/TagCheckViewController.swift
  Bragit/Presentation/ Auth/Temrs/TermsViewController.swift
  Bragit/Presentation/ Auth/Terms/TermsViewController.swift
  Bragit/Resources/Assets.xcassets/Accept.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/Accept.imageset/Union.pdf
  Bragit/Resources/Assets.xcassets/reject.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/reject.imageset/Exclude.pdf
Labels: 📦 Add, ✨ Feat, 🔨 Refactor, 🗑️ Remove

#47 ✨ Feat: 게시글 미리보기 화면 UI
  Bragit.xcodeproj/project.pbxproj
  Bragit/App/Flow/AppStep.swift
  Bragit/App/Flow/WriteFeedFlow.swift
  Bragit/Managers/TagManager.swift
  Bragit/Model/PostDraft.swift
  Bragit/Model/PreviewModel.swift
  Bragit/Presentation/DesignSystem/Alert.swift
  Bragit/Presentation/DesignSystem/DescriptionTextView.swift
  Bragit/Presentation/DesignSystem/EditorAccessoryView.swift
  Bragit/Presentation/DesignSystem/EditorView.swift
  Bragit/Presentation/DesignSystem/SerachBar.swift
  Bragit/Presentation/Write/FeedWrite/WriteReactor.swift
  Bragit/Presentation/Write/FeedWrite/WriteViewController.swift
  Bragit/Presentation/Write/Preview/Cell/AddImageCell.swift
  Bragit/Presentation/Write/Preview/Cell/DescriptionCell.swift
  Bragit/Presentation/Write/Preview/Cell/HeaderView.swift
  Bragit/Presentation/Write/Preview/Cell/TagCell.swift
  Bragit/Presentation/Write/Preview/Cell/ThumbnailCell.swift
  Bragit/Presentation/Write/Preview/Cell/TitleCell.swift
  Bragit/Presentation/Write/Preview/PreviewReactor.swift
  Bragit/Presentation/Write/Preview/PreviewViewController.swift
  Bragit/Presentation/Write/SearchTag/SearchTagReactor.swift
  Bragit/Presentation/Write/SearchTag/SearchTagViewController.swift
  Bragit/Resources/Assets.xcassets/back.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/back.imageset/back.pdf
  Bragit/Resources/Assets.xcassets/camera.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/camera.imageset/camera_plus.pdf
  Bragit/Resources/Assets.xcassets/check.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/check.imageset/circle_check.pdf
  Bragit/Resources/Assets.xcassets/plus.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/plus.imageset/plus.pdf
  Bragit/Resources/Assets.xcassets/primary100.colorset/Contents.json
Labels: ✨ Feat

#53 💡 Chore: 게시글의 태그 이벤트 VC 까지 연결
  Bragit/Presentation/DesignSystem/FeedView.swift
  Bragit/Presentation/Favorite/FavoriteFeedView.swift
  Bragit/Presentation/Favorite/FavoriteViewController.swift
  Bragit/Presentation/Home/HomeViewController.swift
  Bragit/Presentation/Home/PostCell.swift
  Bragit/Presentation/Home/TagsView.swift
  Bragit/Presentation/MyPage/MyPageView.swift
  Bragit/Presentation/MyPage/MyPageViewController.swift
Labels: 💡 Chore

#57 Feat/#56 post detail data
  Bragit/App/Flow/AppStep.swift
  Bragit/App/Flow/FavoriteFlow.swift
  Bragit/App/Flow/HomeFlow.swift
  Bragit/App/Flow/MyPageFlow.swift
  Bragit/App/Flow/TabFlow.swift
  Bragit/Presentation/DesignSystem/FeedView.swift
  Bragit/Presentation/DetailPost/DetailPostReactor.swift
  Bragit/Presentation/DetailPost/DetailPostViewController.swift
  Bragit/Presentation/Home/HomeReactor.swift
  Bragit/Presentation/Home/HomeViewController.swift
Labels: ✨ Feat

#61 ✨Feat: 디자인 적용 및 가입 단계 태그 입력
  Bragit/App/Flow/AppStep.swift
  Bragit/App/Flow/LoginFlow.swift
  Bragit/App/Flow/TabFlow.swift
  Bragit/Presentation/ Auth/ImageUpload/ImageUploadReactor.swift
  Bragit/Presentation/ Auth/ImageUpload/ImageUploadViewController.swift
  Bragit/Presentation/ Auth/Login/LoginReactor.swift
  Bragit/Presentation/ Auth/Login/LoginViewController.swift
  Bragit/Presentation/ Auth/SignUp/UserInfoViewController.swift
  Bragit/Presentation/ Auth/TagCheck/TagCheckReactor.swift
  Bragit/Presentation/ Auth/TagCheck/TagCheckViewController.swift
  Bragit/Presentation/ Auth/Terms/TermsViewController.swift
  Bragit/Presentation/Comment/CommentReactor.swift
  Bragit/Presentation/Comment/CommentViewController.swift
  Bragit/Resources/Assets.xcassets/ accept.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/ accept.imageset/Union.pdf
  Bragit/Resources/Assets.xcassets/check.imageset/check.pdf
  Bragit/Resources/Assets.xcassets/systemSafe.colorset/Contents.json
  Bragit/Util/LocalStorage.swift
Labels: 📦 Add, 💡 Chore, ✨ Feat, 🔨 Refactor, 🎨 Style, 🗑️ Remove

#68 ✨ Feat: 게시글 상세보기 화면 구현
  Bragit/Managers/PostManager.swift
  Bragit/Managers/StubPostManager.swift
  Bragit/Model/LocalStorageCase.swift
  Bragit/Presentation/DetailPost/DetailPostReactor.swift
  Bragit/Presentation/DetailPost/DetailPostViewController.swift
  Bragit/Presentation/Write/FeedWrite/WriteViewController.swift
  Bragit/Resources/Assets.xcassets/check.imageset/check.pdf
Labels: 📦 Add, ✨ Feat

#70 📦 Add: 로고 및 스플래시 앱아이콘 적용
  Bragit.xcodeproj/project.pbxproj
  Bragit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bragit/App/Flow/AppFlow.swift
  Bragit/App/Flow/AppStep.swift
  Bragit/Presentation/ Auth/Login/LoginViewController.swift
  Bragit/Presentation/Home/HomeView.swift
  Bragit/Presentation/Splash/SplashViewController.swift
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/icon_llight 1.png
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/icon_llight 2.png
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/icon_llight 3.png
  Bragit/Resources/Assets.xcassets/LaunchScreen.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/LaunchScreen.imageset/image 412.pdf
  Bragit/Resources/Assets.xcassets/headerLogo.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/headerLogo.imageset/logo_black.pdf
  Bragit/Resources/Assets.xcassets/loginLogo.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/loginLogo.imageset/image_login 1.pdf
  Bragit/Resources/Base.lproj/LaunchScreen.storyboard
  Bragit/Resources/Lottie/splash.lottie
Labels: 📦 Add, ✨ Feat

#78 📝 Docs: Lint Role 변경
  .swiftlint.yml
Labels: 📝 Docs

#79 ✨ Feat : #77 유저 프로필 변경 기능 추가
  Bragit/App/SceneDelegate.swift
  Bragit/Managers/PostManager.swift
  Bragit/Managers/UserManager.swift
  Bragit/Presentation/Home/HomeReactor.swift
  Bragit/Presentation/Home/PostCell.swift
  Bragit/Presentation/MyPage/MyPageProfileCell.swift
  Bragit/Presentation/MyPage/MyPageReactor.swift
  Bragit/Presentation/MyPage/MyPageView.swift
  Bragit/Presentation/MyPage/MyPageViewController.swift
Labels: ✨ Feat

#82 ✨ Feat: 검색 DB연결
  Bragit/App/Flow/AppStep.swift
  Bragit/App/Flow/TabFlow.swift
  Bragit/Managers/SearchManager.swift
  Bragit/Model/DependencyKeys.swift
  Bragit/Model/LocalStorageCase.swift
  Bragit/Model/PreviewModel.swift
  Bragit/Model/SearchModel.swift
  Bragit/Presentation/DesignSystem/SerachBar.swift
  Bragit/Presentation/DetailPost/DetailPostViewController.swift
  Bragit/Presentation/Favorite/FavoriteReactor.swift
  Bragit/Presentation/Favorite/FavoriteView.swift
  Bragit/Presentation/Favorite/FavoriteViewController.swift
  Bragit/Presentation/Home/HomeReactor.swift
  Bragit/Presentation/Home/HomeView.swift
  Bragit/Presentation/Home/HomeViewController.swift
  Bragit/Presentation/Search/SearchReactor.swift
  Bragit/Presentation/Search/SearchViewContoller.swift
  Bragit/Presentation/Write/FeedWrite/WriteViewController.swift
  Bragit/Presentation/Write/Preview/Cell/HeaderView.swift
  Bragit/Presentation/Write/Preview/PreviewViewController.swift
  Bragit/Presentation/Write/SearchTag/SearchTagViewController.swift
  Bragit/Resources/Assets.xcassets/clock.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/clock.imageset/clock.pdf
  Bragit/Resources/Assets.xcassets/hashTag.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/hashTag.imageset/hashtag.pdf
Labels: 📦 Add, ✨ Feat, 🔨 Refactor

#85 Chore/#65 comment
  Bragit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bragit/Model/Comment.swift
  Bragit/Presentation/Comment/CommentReactor.swift
  Bragit/Presentation/Comment/CommentViewController.swift
  Bragit/Resources/Assets.xcassets/lock.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/lock.imageset/lock.pdf
  Bragit/Resources/Assets.xcassets/send.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/send.imageset/send.pdf
  Bragit/Resources/Assets.xcassets/unlock.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/unlock.imageset/unlock.pdf
Labels: 📦 Add, ✨ Feat, 🚨 Fix, 🔨 Refactor, 🎨 Style, 🗑️ Remove

#90 ✨ Feat: #80 탈퇴하기 기능 구현
  Bragit/App/Flow/AppStep.swift
  Bragit/App/Flow/LoginFlow.swift
  Bragit/Managers/UserManager.swift
  Bragit/Model/User.swift
  Bragit/Presentation/ Auth/Login/LoginReactor.swift
  Bragit/Presentation/ Auth/Login/LoginViewController.swift
  Bragit/Presentation/ Auth/SignUp/UserInfoViewController.swift
  Bragit/Presentation/ Auth/TagCheck/TagCheckReactor.swift
  Bragit/Presentation/ Auth/Terms/TermsViewController.swift
  Bragit/Presentation/MyPage/MyPageSub/CancelAccount/CancelAccountReactor.swift
  Bragit/Presentation/MyPage/MyPageSub/CancelAccount/CancelAccountViewController.swift
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/icon_llight 1.jpg
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/icon_llight 1.png
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/icon_llight 2.jpg
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/icon_llight 2.png
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/icon_llight 3.jpg
  Bragit/Resources/Assets.xcassets/AppIcon.appiconset/icon_llight 3.png
Labels: ✨ Feat

#104 ✨ Feat: 검색 페이징 기능
  Bragit/Presentation/Search/SearchReactor.swift
  Bragit/Presentation/Search/SearchViewContoller.swift
Labels: ✨ Feat

#112 ✨ Feat: #91 유저 프로필 구현
  Bragit/Managers/BlockManager.swift
  Bragit/Managers/ReportManager.swift
  Bragit/Managers/UserManager.swift
  Bragit/Model/DependencyKeys.swift
  Bragit/Model/Profile.swift
  Bragit/Presentation/Favorite/FavoriteViewController.swift
  Bragit/Presentation/Home/HomeViewController.swift
  Bragit/Presentation/MyPage/MyPageViewController.swift
  Bragit/Presentation/MyPage/MyPostsHeader.swift
  Bragit/Presentation/UserProfile/UserProfileCell.swift
  Bragit/Presentation/UserProfile/UserProfileReactor.swift
  Bragit/Presentation/UserProfile/UserProfileView.swift
  Bragit/Presentation/UserProfile/UserProfileViewCotnroller.swift
Labels: ✨ Feat

#123 🚨 Fix: 유저프로필 컬렌션뷰 하단 세이프 에리어로 잡혀있는거 수정
  Bragit/Presentation/UserProfile/UserProfileView.swift
Labels: 🚨 Fix

#121 🚨: HeaderView 및 각종 버그 수정
  Bragit/App/Flow/LoginFlow.swift
  Bragit/Presentation/ Auth/ImageUpload/ImageUploadReactor.swift
  Bragit/Presentation/ Auth/ImageUpload/ImageUploadViewController.swift
  Bragit/Presentation/ Auth/Login/LoginViewController.swift
  Bragit/Presentation/ Auth/MailLogin/MailLoginViewController.swift
  Bragit/Presentation/ Auth/SignUp/UserInfoViewController.swift
  Bragit/Presentation/ Auth/TagCheck/TagCheckReactor.swift
  Bragit/Presentation/ Auth/TagCheck/TagCheckViewController.swift
  Bragit/Presentation/ Auth/Terms/SignTermsReactor.swift
  Bragit/Presentation/ Auth/Terms/SignTermsViewController.swift
  Bragit/Presentation/ Auth/Terms/TermsViewController.swift
  Bragit/Presentation/Comment/CommentViewController.swift
  Bragit/Presentation/MyPage/Setting/SettingDepth/TermsOfUse/SettingTermsDetailViewController.swift
Labels: 📦 Add, 🚨 Fix, 🚀 Perf, 🔨 Refactor, 🎨 Style

#146 ✨ Feat : #145 마이페이지 하위(팔로잉, 팔로워, 관심태그)에서 이동 로직 구현
  Bragit/Presentation/MyPage/MyPageSub/FavoriteTagsReactor.swift
  Bragit/Presentation/MyPage/MyPageSub/FavoriteTagsViewController.swift
  Bragit/Presentation/MyPage/MyPageSub/FollowerReactor.swift
  Bragit/Presentation/MyPage/MyPageSub/FollowerVIewController.swift
  Bragit/Presentation/MyPage/MyPageSub/FollowingReactor.swift
  Bragit/Presentation/MyPage/MyPageSub/FollowingViewController.swift
  Bragit/Presentation/MyPage/MyPageSub/ProfileListViewController.swift
Labels: ✨ Feat

#153 Fix : #152 게시글 새로고침 관련 수정
  Bragit/Presentation/DesignSystem/FeedView.swift
  Bragit/Presentation/Favorite/FavoriteFeedView.swift
Labels: 🚨 Fix

#154 🚨 Fix: 각종 버그 및 자잘한 기능 추가
  Bragit.xcodeproj/project.pbxproj
  Bragit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bragit/Model/TostModel.swift
  Bragit/Presentation/Comment/CommentReactor.swift
  Bragit/Presentation/Comment/CommentViewController.swift
  Bragit/Presentation/DesignSystem/Alert.swift
  Bragit/Presentation/DetailPost/DetailPostReactor.swift
  Bragit/Presentation/DetailPost/DetailPostViewController.swift
  Bragit/Presentation/MyPage/Setting/SettingDepth/OpenSourceLicense/LicenseReactor.swift
  Bragit/Presentation/MyPage/Setting/SettingDepth/TermsOfUse/SettingTermsReactor.swift
  Bragit/Presentation/Write/FeedWrite/WriteViewController.swift
  Bragit/Presentation/Write/Preview/Cell/DescriptionCell.swift
  Bragit/Presentation/Write/Preview/PreviewReactor.swift
  Bragit/Presentation/Write/Preview/PreviewViewController.swift
  Bragit/Presentation/Write/SearchTag/SearchTagReactor.swift
  Bragit/Presentation/Write/SearchTag/SearchTagViewController.swift
  Bragit/Resources/License/LICENSE_Loaf.txt
  Bragit/Resources/TermsOfUse/Terms_Service.txt
Labels: 📦 Add, 💡 Chore, 📝 Docs, ✨ Feat, 🚨 Fix, 🔨 Refactor

#158 🚨: 앱 재설치 때 블록, 팔로우 유저 못 가져오던 문제 수정
  Bragit/App/SceneDelegate.swift
  Bragit/Presentation/ Auth/Login/LoginReactor.swift
Labels: 🚨 Fix

#159 🚀 Perf: 고용량 사진을 업로드하면 메모리가 심각하게 많이 사용되어 과부하가 걸리는 문제 해결
  Bragit.xcodeproj/project.pbxproj
  Bragit/Model/PreviewModel.swift
  Bragit/Presentation/DesignSystem/EditorView.swift
  Bragit/Presentation/Write/Preview/PreviewReactor.swift
  Bragit/Presentation/Write/Preview/PreviewViewController.swift
  Bragit/Util/UIImage++.swift
Labels: 🚨 Fix, 🚀 Perf

#165 🚀 Perf: 임시저장 및 이미지 로직
  Bragit/Presentation/DetailPost/DetailPostViewController.swift
  Bragit/Presentation/Write/FeedWrite/WriteReactor.swift
  Bragit/Presentation/Write/FeedWrite/WriteViewController.swift
  Bragit/Presentation/Write/Preview/PreviewReactor.swift
Labels: ✨ Feat, 🚀 Perf

#168 ✨ Feat: UT 버그 및 피드백 반영
  Bragit/App/Flow/SearchFlow.swift
  Bragit/Managers/SearchManager.swift
  Bragit/Managers/TagManager.swift
  Bragit/Presentation/DetailPost/DetailPostReactor.swift
  Bragit/Presentation/Search/SearchReactor.swift
  Bragit/Presentation/Search/SearchViewContoller.swift
Labels: ✨ Feat, 🚨 Fix, 🚀 Perf, 🔨 Refactor

#169 Docs : #164 리드미 초안
  Bragit.xcodeproj/project.pbxproj
  README.md
Labels: 📝 Docs

#172 🚨 Fix : #171 여러 버그 수정
  Bragit.xcodeproj/project.pbxproj
  Bragit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bragit/Presentation/Favorite/FavoriteFeedView.swift
  Bragit/Presentation/Favorite/FavoriteReactor.swift
  Bragit/Presentation/Favorite/FavoriteViewController.swift
  Bragit/Presentation/Home/HomeReactor.swift
  Bragit/Presentation/MyPage/MyPageReactor.swift
  Bragit/Presentation/UserProfile/UserProfileView.swift
Labels: 🚨 Fix

#173 🚨 Fix: 각종 버그사항들
  Bragit/Presentation/DesignSystem/EditorAccessoryView.swift
  Bragit/Presentation/DesignSystem/LimitedMenuTextView.swift
  Bragit/Presentation/DetailPost/DetailPostViewController.swift
  Bragit/Presentation/Search/SearchReactor.swift
  Bragit/Presentation/Search/SearchViewContoller.swift
Labels: 🚨 Fix, 🚀 Perf
