Repository Brag-it/Bragit, pull requests merged in 2025-08, with the labels that each got.

#5 ✨ Feat: 하단 탭바
  Bragit/App/SceneDelegate.swift
  Bragit/Presentation/Favorite/FavoriteViewController.swift
  Bragit/Presentation/Home/HomeViewController.swift
  Bragit/Presentation/MyPage/MyPageViewController.swift
  Bragit/Presentation/Write/WriteViewController.swift
  Bragit/Resources/Assets.xcassets/favorite.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/favorite.imageset/heart 1.png
  Bragit/Resources/Assets.xcassets/favorite.imageset/heart 2.png
  Bragit/Resources/Assets.xcassets/favorite.imageset/heart.png
  Bragit/Resources/Assets.xcassets/home.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/home.imageset/home 1.png
  Bragit/Resources/Assets.xcassets/home.imageset/home 2.png
  Bragit/Resources/Assets.xcassets/home.imageset/home.png
  Bragit/Resources/Assets.xcassets/mypage.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/mypage.imageset/my 1.png
  Bragit/Resources/Assets.xcassets/mypage.imageset/my 2.png
  Bragit/Resources/Assets.xcassets/mypage.imageset/my.png
  Bragit/Resources/Assets.xcassets/write.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/write.imageset/plus_box 1.png
  Bragit/Resources/Assets.xcassets/write.imageset/plus_box 2.png
  Bragit/Resources/Assets.xcassets/write.imageset/plus_box.png
Labels: ✨ Feat

#15 Feat/#10 메인 피드 리엑터 구현
  .swiftlint.yml
  Bragit/Managers/PostManager.swift
  Bragit/Managers/StubPostManager.swift
  Bragit/Model/DependencyKeys.swift
  Bragit/Model/Post.swift
  Bragit/Presentation/Home/HomeReactor.swift
  BragitTests/BragitTests.swift
Labels: ✨ Feat

#14 ✨: Sign in with Apple
  Bragit.xcodeproj/project.pbxproj
  Bragit/Bragit.entitlements
  Bragit/Managers/Auth/AuthClient.swift
  Bragit/Model/DependencyKeys.swift
  Bragit/Presentation/ Auth/Login/LoginReactor.swift
  Bragit/Presentation/ Auth/Login/LoginViewController.swift
  Bragit/Presentation/DesignSystem/Alert.swift
  Bragit/Resources/Assets.xcassets/mail.imageset/Contents.json
  Bragit/Resources/Assets.xcassets/mail.imageset/mail.pdf
Labels: 📦 Add, ✨ Feat, 🔨 Refactor, 🎨 Style

#26 Feat/#22 sign up page
  Bragit/Presentation/ Auth/Login/LoginReactor.swift
  Bragit/Presentation/ Auth/Login/LoginViewController.swift
  Bragit/Presentation/ Auth/SignUp/KeychainHelper.swift
  Bragit/Presentation/ Auth/SignUp/KeychainMailStore.swift
  Bragit/Presentation/ Auth/SignUp/UserInfoViewController.swift
  Bragit/Presentation/ Auth/Temrs/TermsViewController.swift
Labels: 📦 Add, ✨ Feat, 🔨 Refactor

#34 🚨: 로직 수정
  Bragit/Presentation/ Auth/Login/LoginReactor.swift
  Bragit/Presentation/ Auth/Login/LoginViewController.swift
Labels: 🚨 Fix, 🎨 Style
